### ISSUE TITLE
There are two configuration files for conversion plugins. We should have only one?

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1003]
roda-core.properties has some of the properties, and roda-core-format.properties has some other properties. 

Why not include all the properties related to conversion plugins under the same file?

@hsilva-keep and @luis100, I would like your comments on this please.

**Comment by hsilva-keep** [comment]
I'm not quiet sure about the reasons, but in roda-core-formats.properties are only properties related to formats, whereas in roda-core.properties are all the other properties of the plugins.

**Comment by luis100** [comment]
I think that having all configurations on roda-core.properties is a pain for implementations, because they only want to override things like SOLR server connection or email SMTP servers but have to keep in sync with all plugin configurations that 99% of the time will want to keep to defaults.
Also, some external plugin having to have configuration on the roda-core.properties is a bit odd.

On the other hand, having one properties file for each plugin might also be a pain, many will only have one or two options.

Maybe we could have a more intelligent system where all properties can be together on one file or divided (like in a conf.d folder) but only need to have the properties one would want to override, merging with the default configuration present in the source code (maybe using commons-configuration?). Property key collision would be avoided with namespaces.

**Comment by hsilva-keep** [comment]
For external plugins, an issue has been created already: #785

**Comment by hsilva-keep** [comment]
In what concerns properties & properties loading, at least there is already one issue to enhance them: #998.

**Comment by jmaferreira** [comment]
Why not generalising the plugins properties into one file called roda-plugins.properties.

It would have all the stuff about plugins that is currently on the other two files.

Internal plugins should stay on the core properties though.

**Comment by hsilva-keep** [comment]
With the removal of the plugins module , this configuration was removed & therefore this issue no longer applies.
