### ISSUE TITLE
Make dbviewer iframe fullheight

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1044]
Listen to the iframe onload and after loading set the iframe height based on the iframe's content scroll height.

**Comment by chalkos** [comment]
This was fixed using https://github.com/davidjbradshaw/iframe-resizer

This library requires the parent page to use a specific "host" javascript and the iframe page to use a specific "guest" javascript (because the library actually sends messages between the main page and the iframe page in order to work around cross-site scripting security policies).

**NOTE FOR FUTURE EXTERNAL DIP VIEWERS:**
To make iframe resizing work with DIPs that use "dipExternalUrl" and are embed in RODA, the page being loaded inside the iframe must include the "guest" javascript (named `iframeResizer.contentWindow.min.js` and included in RODA for simplicity and to avoid version mismatch).

The database visualization toolkit includes the iframe resizer guest javascript starting with version 1.0.2
