### ISSUE TITLE
Advanced search: combo appears on the wrong place

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1096]
Scroll down and this happens:

![screen shot 2017-11-23 at 16 37 50](https://user-images.githubusercontent.com/3181302/33182652-c538dc40-d06c-11e7-9bc4-43a98602a43f.png)

**Comment by jmaferreira** [comment]
@luis100 Just to make it clear for everyone. I went back and checked version 2.0 (docker) and the problem does not manifest it self in that version. Have fun!

**Comment by chalkos** [comment]
![screenshot from 2017-11-24 15-56-09](https://user-images.githubusercontent.com/98429/33217468-06352352-d130-11e7-9c5b-b9136f3de3e5.png)

I was not able to reproduce the problem with the default configs on the latest version (i even tried scrolling down, it still works)

**Comment by chalkos** [comment]
Can you try going back to the version in which you initially experienced the problem and see if it is still present? Are you using the default configs?

**Comment by jmaferreira** [comment]
The problem is present on container keeps/roda:2.2.0-beta1 with the default configs.

The problem was detected on my Mac (safari) and on @luis100 Linux (chrome).

**Comment by jmaferreira** [comment]
One more interesting bit of information. On chrome@MacOS I cannot reproduce it as well.

**Comment by chalkos** [comment]
This seems to be more complex than expected.

Testing with MacOS, both roda instances having the default config:

with docker version 2.0:
* chrome: bug
* safari: ok
* firefox: ok

with docker version 2.2.0-beta1:
* chrome: ok
* safari: bug
* firefox: bug

We may need to isolate the component/problem and work from there. There is a similar issue (but in this case the problem is the datepicker, #1072), maybe http://samples.gwtproject.org/samples/Showcase/Showcase.html#!CwDatePicker can be used in our tests.

**Comment by jmaferreira** [comment]
Check this: 
https://stackoverflow.com/questions/46659830/gwt-popup-in-wrong-position-for-latest-chrome-version

**Comment by jmaferreira** [comment]
And this:
https://github.com/gwtproject/gwt/issues/9542

**Comment by hsilva-keep** [comment]
"This bug has been fixed in GWT version 2.8.2" & we still use GWT version 2.7.0

**Comment by jmaferreira** [comment]
Try updating to see if it breaks anything...

**Comment by chalkos** [comment]
GWT updated on development branch. It fixes this for some cases, but not all. No problems have been detected yet.

**Comment by jmaferreira** [comment]
Could not replicate anymore.
Closing this one.
