### ISSUE TITLE
Error transforming preservation event details into HTML

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#1192]
![screen shot 2018-03-28 at 14 57 28](https://user-images.githubusercontent.com/3181302/38033682-772aa536-3298-11e8-9e87-bfdd90da102d.png)
<img width="1337" alt="screen shot 2018-03-28 at 14 57 24" src="https://user-images.githubusercontent.com/3181302/38033683-77450c5a-3298-11e8-90c0-16d9ff48a922.png">

@luis100 please delegate in the right person.

**Comment by hsilva-keep** [comment]
Problem was introduced in 709954d828a214888e8dc2adeeb49b7cbe776440

**Comment by chalkos** [comment]
The problem was introduced more than a year ago (bad copy paste).

Some unidentified side-effect of having `Authorization: Custom` header was allowing the api call to go through, and when that header was removed the request started to be refused because it did not contain any json nor xml for the server to consume.

**Comment by chalkos** [comment]
The fix is under testing.

**Comment by chalkos** [comment]
Tested with internal auth and CAS auth (both internal LDAP login and CAS login)
