### ISSUE TITLE
Delete AIP(s) 1.0 error

### ISSUE THREAD

**Issue by GolikSwe** [keeps/roda#1233]
There is a bug in “new process”; select Delete AIP (s) (1.0).
If you do not make any selection in the checkboxes, ie leave them blank and you then select button "Create". Even if you have not made any selection, all your AIPs are deleted.
This is not good.

**Comment by luis100** [comment]
Hi @GolikSwe, we do not consider this a bug, the convention for all plugins is that if no object is selected then the action is executed in all objects (iterated via model instead of index, to enable actions like re-index). But, I do understand that this may be very destructive in the case of the Delete AIPs plugin.

The access to actions should be very controlled (only available to admin users) as there is no control of the damage that a plugin might introduce in the system.

We might consider this an usability problem, as the user might not be aware of the implication of their actions. To this we offer these (not excluding) options to be considered in future roadmap:

- A confirmation dialog that would explain the implications of the actions (which plugin is executing into which objects) and might require the user to transcribe the object title into a text box (in case just one is selected) or to transcribe the number of objects if it is known, or to transcribe `All intellectual entities` if all are selected.
- Have a different way to select all objects that would not be based on selecting none (suggestions?)

Do you have any feedback on these options or other suggestions you can provide us to solve this?

**Comment by GolikSwe** [comment]
	We suggest improvement of the delete process operation in the following way:	
	1. That if no intellectual entity or AIP is selected that no entity is deleted. Is that not more logical? 
If no one is selected nothing is done. At least for destructive operations like Delete.
	
	2. When *selecting* the Delete Process Operation the user has the possibility to choose with checkbox ”|X|   Delete only the AIPs and keep the archival structure/the intellectual entities.”
After pressing the ”Create Delete Job”-button the user is presented with the confirmation dialog
”This will delete all AIPs that are stored in the intellectual entity {Title of intellectual entity} and the intellectual entities below. {And if the checkbox is not checked: ”This will also delete all intellectual entities.”} This action is not reversible. Do you want to start the delete process? (Y/N)”.

**Comment by luis100** [comment]
> That if no intellectual entity or AIP is selected that no entity is deleted. Is that not more logical?
> If none is selected nothing is done. At least for destructive operations like Delete.

This option would mean a deep change on the interface, which we might consider in the future roadmap but that will take a lot of time and effort. We might want to consider other options to mitigate the problem.

One option would be to simply hide the Remove AIP plugin from the New Process plugins list. This plugin is already used when remove action are issued on the Web interface by using the REMOVE button or Actions > REMOVE in lists. When using in this way, confirmation dialogs are already shown and reason descriptions are required to put on the preservation metadata that is generated by these actions.

> When selecting the Delete Process Operation the user has the possibility to check a checkbox like this: ”|X| Delete only the AIPs and keep the archival structure/the intellectual entities.”

I must say I don't really understand what is meant by deleting the AIP but keeping the intellectual entity. In RODA we consider AIP (as defined in OAIS) and Intellectual Entity (as defined in PREMIS) are equivalent as one AIP contains an Intellectual Entity. I don't want to enter into a terminology discussion, but this is just to say I do not understand want is meant by deleting the AIP but not the Intellectual Entity when in RODA.

> Then after pressing the ”Create Delete Job”-button the user is presented with the confirmation dialog like this: ”This will delete all AIPs that are stored in the intellectual entity {Title of intellectual entity} and the intellectual entities below. {And if the checkbox is not checked: ”This will also delete all intellectual entities.”} This action is not reversible. Do You want to start this delete process? (Y/N)”.

As said above, when using the REMOVE button care is already taken to show confirmation dialogs to the user and ask for a reason to put afterwards in the preservation metadata. So I re-state that hiding the plugin from the preservation action list would suffice to fix the problem for now.

**Comment by annmak** [comment]
@luis100 
> One option would be to simply hide the Remove AIP plugin from the New Process plugins list. 

How do we hide the RemoveAIP(s) plugin from the New Process list? Do you mean that we put it in roda-core.properties like 
**core.plugins.blacklist = org.roda.core.plugins.plugins.base.RemoveAIPPlugin** 

Can the plugin still be used by roda-core in use of the REMOVE button then? 
Or is there another way to hide the Remove AIP plugin?

**Comment by luis100** [comment]
We would have to add the category RodaConstants.PLUGIN_CATEGORY_NOT_LISTABLE to the plugin source code, or allow it to defined via a configuration. So this would be a feature request.

**Comment by annmak** [comment]
@luis100 
But how are we then supposed to hide it? Can we hide it by user authorization then?

**Comment by hsilva-keep** [comment]
Now, a more generic & internal (not listable in the UI) plugin is used to delete RODA objects. So, this problem no longer applies.
Closing without further actions.
