### ISSUE TITLE
Support for batch disposal of AIP (given a search criteria)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#125]
R64, R65

**Comment by sleroux-keep** [comment]
Added Browser method to export AIP based on a Filter
`public static StreamResponse exportAIP(RodaUser user, Filter filter, String acceptFormat)`

I've also update the REST method /aips/[aipID] GET endpoint to download the AIP Zip representation (better than new ApiResponseMessage(ApiResponseMessage.OK, "magic!") ... )

**Comment by luis100** [comment]
The method `Browser#removeAIP(RodaUser user, SelectedItems aips)` already allows to delete an AIP based on a Filter. Please **remove** your method `Browser#deleteAIPs(RodaUser user, Filter filter)` because it is duplicate code.

The point of this method is to provide a management tool (the management REST method) that allows to actually perform this method. Please add the method to the REST endpoint `ManagementTasksResource`.

**Comment by jmaferreira** [comment]
Whats the status of this issue?

**Comment by sleroux-keep** [comment]
https://github.com/keeps/roda/blob/master/roda-core/roda-core/src/main/java/org/roda/core/plugins/plugins/base/RemoveAIPPlugin.java

**Comment by luis100** [comment]
- [ ] Create report in case of failure

**Comment by sleroux-keep** [comment]
Done

**Comment by luis100** [comment]
checked.
