### ISSUE TITLE
Authenticating using REST API through another application

### ISSUE THREAD

**Issue by nureynisow** [keeps/roda#1456]
Hello, 

I'm working on an administrative application that have to collect scanned document. At the end of my workflow i have to put the documents in RODA to get them archived.
At the end of the process I call an async method that will post all documents in RODA then ask it to ingest them. 

My first problem is with the authentication. I don't see how to get a RODA user authenticated via the REST API and use the authentication information retrieved (cookie or another token) to perform other request to RODA. 
For your information, I used the Swagger UI to test it but it took the user from the cookies of my browser. 
I also look at the source code which get the user from the HttpRequest Session object. If I don't have any solution Tuesday 19/03, I will fork the code and change the authentication mechanism.

Thanks for your reading and help.

Regards,
Ousmane

**Comment by luis100** [comment]
If the RODA you are connecting to is only using the internal authentication mechanism (instead of connected to an external one) then you simply need to send credentials via basic authentication in every request. You can also use a cookie jar to maintain authentication cookies for multiple requests. 

Please note that to ingest you first need to add files to transfer and then create an ingest job. You can use the "obtain command" Button on the GUI to get you the rest method needed
