### ISSUE TITLE
RODA allows users to download content in spite of setting not to show content. 

### ISSUE THREAD

**Issue by elbre** [keeps/roda#1471]
Hi,
Is there any option how to ban group of users from downloading content of the files? Through user management service I am able to hide from group some parts, but Permisson itself, when is settled to read, approve the user to download even things he is not allowed to see. I thought that maybe setting different Status to representations will have some effect to accesibility, but it does not show any changes. Am I missing some part of user management settings or ONLY READ is not a option?

**Comment by luis100** [comment]
There are two level of permissions, repository level permissions (defined in Administration > Users and Groups, Edit user, Permissions) and object level permissions (open an object/intellectual entity in the Catalogue, actions dropdown in the top-right corner, Permissions).

In the repository level permissions, or user permissions, you can you can remove the permissions to "Retrieve representations and computer files" to a user or group. Also, you have to explicitly add permissions to READ an object/intellectual entity/collection/series. The object permissions will be inherited from parent on ingest.

There is no permission to disable download as you cannot effectively allow to access but disallow download as many times download is the only way to access. But there is a workaround, you can use the new Portal feature (available since [3.1.0](https://github.com/keeps/roda/releases/tag/v3.1.0) but not yet documented :disappointed:), that gives only access to metadata and DIPs, and create DIPs that do not allow download like images previewers and PDF previewers (in which download can be disabled).
