### ISSUE TITLE
How to understand installation of RODA "for demonstration"?

### ISSUE THREAD

**Issue by elbre** [keeps/roda#1472]
Hi, 
sorry for asking the another question in a such short time.
Can somebody explain me, how the usage of the RODA works? It sounds probably like a silly question, but I can still see big differences between different versions provided on this site. We manage to pull out RODA by the Docker, like you are suggesting in Installation documentation. But along with this you always write "for demonstrations" which leads to a conclusion, that it is not full package RODA. So if our archive is satisfied with RODA we should do what exactly? Use .war package?

Also, can you explain me, how to adjust our version for some "process" plugins? Because, for example, unoconv is shown in your demo version website, but documentation about it is missing. I thouth, that there will be some licence issue, but in the version 2.0. you wrote how unoconv and other tools get into it. So these plugins are missing because of using RODA "for demonstration" or we are just missing how to implement optional plugins?

Thank you very much for any answer.

**Comment by luis100** [comment]
If you do not do any extra configuration the RODA available on the docker uses an embedded Apache Solr, which is not the recommended way to put into production. You should use a cloud-mode Apache Solr, possibly in several working nodes, able to grow as more information is added. Also, on the demonstration version the information persistence is not configured. The specific way it should put into production varies from institution to institution as it is highly dependent on the available infrastructure. At [KEEPS](https://www.keep.pt/en/produts/roda-long-term-digital-preservation-repository-solution/) we provide a branding and installation service in case you require.

The plugins that were available before were removed in the upgrade, due to some tools having licences and dependencies that could not just be shipped into the docker container. We are in the process of developing a solution for this, as a plugin market that would allow to download and install plugins and their dependencies in the system. In the meanwhile, we can provide them per-request, please contact sales@keep.pt for a complete list of the available plugins. Please note that some might have commercial license.
