### ISSUE TITLE
Is there a discussion group about RODA?

### ISSUE THREAD

**Issue by SeismoReimaliMalm** [keeps/roda#1546]
I am very new to RODA. Is there any discussion groups for it? The problem isn't how but why, technical documentation is excellent but why to use RODA or similar systems isn't. Flowchart of operations would be extremely helpful.

Seismo Malm/XAMK, Finland

**Comment by jmaferreira** [comment]
Dear Seismo,

We encourage everyone to use GitHub as a discussion forum so that questions get fair and equal treatment by the technicians and the community in general.

Regarding your concerns about the "why", maybe you could take a look at the following document. Hop it helps to understand the problem the system aims to solve and why it is important  - https://www.keep.pt/wp-content/uploads/2019/12/WP181216-whitepaper-roda-3_EN.pdf

Regarding the flowchart of operations. The system mirrors the business processes of OAIS. Maybe you could take a look at that document also - https://public.ccsds.org/pubs/650x0m2.pdf
