### ISSUE TITLE
Object PREMIS does not use UUID as objectIdentifierValue

### ISSUE THREAD

**Issue by JelleKleevensVAI** [keeps/roda#1945]
This may lead to duplicate IDs and should be avoided I suppose?

![image](https://user-images.githubusercontent.com/87436774/132316468-7b411c4b-56d0-4b99-9e54-b66f5989f6aa.png)

On the other hand, an Event PREMIS uses a UUID (?) when referencing an object. Where does this UUID come from and how can we see it in the Object PREMIS?

**Comment by luis100** [comment]
PREMIS events that are within the AIP metadata folders and that refer representations or files local to that AIP will use local identifiers to improve the understandibility of the AIP information when it is on its own. These identifiers should be understood in the context there are in (within the AIP or representation preservation metadata folder).

When objects from an outside context are used, then a general identifier must be used. UUIDs are created for AIPs based on a random source, making them a de-centralized unique identifier. UUIDs for representations and files are created using as a base the identifiers for the context they are in. Representation UUIDs use the AIP UUID and the representation local identifier as seed (instead of a random number), and the file UUIDs use the AIP UUID, the representation ID, the file path and the file name as seed.

Nevertheless, I see there is a missmatch between the identifier declared in events that point to files and the identifier declared in the PREMIS object that might bring some confusion.

**Comment by WimLo** [comment]
Hi,

I'd like to add a question in this issue. Regarding the mismatch between identifier declared in events and the identifier declared in the PREMIS object. This is a list of relations to files in a PREMIS event, documenting a format identification event.

```<linkingObjectIdentifier>
    <linkingObjectIdentifierType>URN</linkingObjectIdentifierType>
    <linkingObjectIdentifierValue>urn:roda:file:73f5c4c6-ede9-3bca-93ac-7a78f541b95b</linkingObjectIdentifierValue>
    <linkingObjectRole>source</linkingObjectRole>
  </linkingObjectIdentifier>
  <linkingObjectIdentifier>
    <linkingObjectIdentifierType>URN</linkingObjectIdentifierType>
    <linkingObjectIdentifierValue>urn:roda:file:bf63d1ad-8f21-3e25-8e4a-bd288fb44fe5</linkingObjectIdentifierValue>
    <linkingObjectRole>source</linkingObjectRole>
  </linkingObjectIdentifier>```

What are my options to link the UUID with the actual file, since the UUID is not used as identifier in the PREMIS object metadata?

**Comment by luis100** [comment]
The PREMIS metadata is managed by RODA automatically, so currently there is no other option here to customize how the PREMIS events are created.

What we can do is to add a new identifier in the PREMIS object with the UUID, this would be a new feature to be developed.

Object identifiers are a repeateble element in PREMIS metadata.

![image](https://user-images.githubusercontent.com/631728/132472724-d3cd180a-2745-4b70-a55c-aabbbb2ad931.png)
from: http://www.loc.gov/standards/premis/v3/premis-3-0-final.pdf

With the development of this proposed feature/enhancement, the re-generation of the PREMIS object metadata would update the PREMIS metadata in the following way:

```xml
<v3:object xmlns:v3="http://www.loc.gov/premis/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="v3:file">
  <v3:objectIdentifier>
    <v3:objectIdentifierType>URN</v3:objectIdentifierType>
    <v3:objectIdentifierValue>urn:roda:premis:file:c15cc957-8952-3592-b7e5-85909543fa2c</v3:objectIdentifierValue>
  </v3:objectIdentifier>
  <v3:objectIdentifier>
    <v3:objectIdentifierType>URN-local</v3:objectIdentifierType>
    <v3:objectIdentifierValue>urn:roda:premis:file:DILCISBOARD_E-ARK_AIP_1_0.pdf</v3:objectIdentifierValue>
  </v3:objectIdentifier>
...
</v3:object>
```
Now both local and global identifiers would be present (ensure we don't break backwards compatibility) and we would still have the identifiers necessary correctly correspond events with objects.
