### ISSUE TITLE
Question: Backwards compatability

### ISSUE THREAD

**Issue by karatekaneen** [keeps/roda#2025]
Hi!

Looking into running RODA for a customer. It looks really nice and well maintained, very nice job! 

I saw that you release new versions quite frequently and it would be nice to be able to keep our instance up to date. so my questions are:
1: How backwards compatible is the data? Should it be safe to assume that updating within the same major version would be relatively safe? 
2: On breaking changes, how do you usually handle migrations between versions?

**Comment by luis100** [comment]
Thank you @karatekaneen 

> 1: How backwards compatible is the data? Should it be safe to assume that updating within the same major version would be relatively safe?
> 2: On breaking changes, how do you usually handle migrations between versions?

The most backwards compatible we can. We don't break compatibility even on major version upgrade unless it is unfeasible to do otherwise. There is a file named model.json in the base of the RODA data folder that keeps track on changes in the model and RODA refuses to startup in the off-change it is not compatible and always provides migration scripts to migrate data, but that has not been needed for the past couple of major version releases and we will only use it if we cannot create a backwards compatible model.

Major version upgrade can require you to re-index all entities, which can be done the Web UI. This is mainly needed when Apache Solr backend service needs a major upgrade. To note that such is planned for RODA 5 release which will upgrade Apache Solr from 7.X to 8.X.
