### ISSUE TITLE
Modify SIP to AIP plugins to optionally create submission in AIP

### ISSUE THREAD

**Issue by luis100** [keeps/roda#213]
The option should be a plugin parameter.
Depends on #212

**Comment by hsilva-keep** [comment]
This functionality was added to all SIP2AIP plugins (since 712d6b0dab15fedc650192d48355024fe0580f79), and can set via parameter. In what concerns the DefaultIngestPlugin (and all that extend it) the creation of the submission is off by default but, at the moment, can be activated via roda-core.properties. Latter on one can configure any of the IngestPlugins to put available a parameter to activate the funcionality via WUI.
