### ISSUE TITLE
Processes with different types of parallelism are sharing the same pool of workers

### ISSUE THREAD

**Issue by hmiguim** [keeps/roda#2211]
This makes that some processes will have to wait for that work finishing its tasks. This is particular problematic if one of the tasks takes too long to finish. 

For example, running the inventory report over 20 millions AIPs will cause that some ingest processes or other jobs will have to wait for the inventory report plugin finishes counting the total amount of AIPs.

**Comment by 006627** [comment]
The solution developed by Miguel at 046a5d924285f2c942bb617b3cd9fbb10a3bd768 is working as expected, as soon as possible we will make a new release.

##  Test
It was tested on a 4 CPU machine, using the default orchestration settings.

###  Evidences
1 - When the inventory report process is started with medium priority and normal parallelism, some ingest processes are in waiting state because the orchestration engine is busy doing the inventory report.
![image](https://user-images.githubusercontent.com/10729410/180019970-79bc47e8-0801-4ab1-9a33-2301a0898b61.png)

2 - When the inventory report process is started with low priority and limited parallelism, no ingest processes are in a waiting state.
![image](https://user-images.githubusercontent.com/10729410/180020298-0995b1e6-ad13-477b-b84a-6c9bbbf2226f.png)

**Comment by hmiguim** [comment]
Close at https://github.com/keeps/roda/commit/8a9bf395f9163c4f2653d74bba729db65c51be1f
