### ISSUE TITLE
Strange behaviour in basic search

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#306]
The 2 following queries produce very different results:

1. PT/AMDL/PRQ/AMM02/001/0042
2. PT AMDL PRQ AMM02 001 0042

They should return the same set of results. Is there a good reason not to?

**Comment by jmaferreira** [comment]
@sleroux-keep can you help here? You have been working on the filters and tokenisers recently. Is there any advice you can give?

**Comment by hsilva-keep** [comment]
Solved via 5cd89bde45b86b563445697d2fd690428e4670b1. The problem was due to the lack of default operator declaration. There was two options here: 1) to declare it in each schema.xml; 2) to declare it in the java code that generates a SolrQuery. The second was the one selected as it is the one suggested by Apache Solr guys (see https://wiki.apache.org/solr/SchemaXml#Default_query_parser_operator)

**Comment by jmaferreira** [comment]
Enhance the QueryParser before closing the issue please

**Comment by luis100** [comment]
Try the `SimpleQParserPlugin`

**Comment by luis100** [comment]
The system is working for now, the `SimpleQParserPlugin` will be tested later.
