### ISSUE TITLE
Cannot change to admin password due to an "illegal operation"

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#335]
![screen shot 2016-05-17 at 15 44 45](https://cloud.githubusercontent.com/assets/3181302/15326547/5974ac22-1c46-11e6-8ec9-f3f70b6ea7b0.png)

**Comment by luis100** [comment]
This is not an error but a feature, editing the admin user is disalowed.
Nevertheless, the message should be reviewed, so I would let it open until then.

**Comment by jmaferreira** [comment]
How to I change the admin password then?

**Comment by luis100** [comment]
That is tricky, would need to do it in LDAP low level commands.
Will consider removing the restriction.

**Comment by jmaferreira** [comment]
lol!

I’ll tell you how DSPace handles it. Of course you can change the password on the UI, but in case you want to reset it, there is a command line script on the “bin” folder that resets the password of the administrator.

**Comment by jmaferreira** [comment]
I guess we will be stuck with the default password forever! :)

**Comment by luis100** [comment]
This is actually a configuration in `roda-core.properties`, that lists the protected users and groups. Change default configuration to have no protected users, done since d22a784edbcd06a16d4eba8f7882f04bd59c5499.

Nevertheless, change can only successfully happen in user management, changing password in Profile makes a user loose all permissions, see #348.
