### ISSUE TITLE
During ingest, if the job crashes (e.g. Java Heap Memory) the Job is not terminated gracefully.

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#337]
This forces the user to restart tomcat and even after that the Job is not reset to a correct faulty state. It stays in the running stage forever.

This probably happens in every Job type, not only ingest jobs.
Rule of thumb: **A Job CAN NOT crash the entire repository, just the job it self**

Buttons must be added to enable the admin to cancel/stop Jobs.

**Comment by hsilva-keep** [comment]
The fact of the Job was not being reset properly during startup when in the state CREATED or STARTED was due to a bug and it was fixed via bfbdfb6e60d95923e98c85cd9172250e65fbb859.

In what concerns running Job/Plugin orchestration outside the application providing the Web User Interface, that will not be tackled in time of the 2.0.0 release and therefore must be scheduled for a future version.

**Comment by jmaferreira** [comment]
Is it possible to run in the same hardware two instances of RODA: one with the catalogue for providing access and another to handle ingest. That would solve the issue nicely.

Solr would have to be centralised. Storage would have to be shared.

**Comment by jmaferreira** [comment]
Will create a new issue for the orchestration part.
