### ISSUE TITLE
Mismatch between roles in roda-roles.properties & roda-wui.properties

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#476]
With the new way to define roles, i.e. class/method oriented, it doesn't make sense anymore to have a static way (roda-wui.properties) to define roles (and possibly their order).

**Comment by luis100** [comment]
Also:

- [ ] Review the roles, as some could me more granular, and other could be deleted (like the ones related to User, RodaUser and RodaGroup instead of RodaMember
- [ ] Review the association between menu entries and roles (will possibly need to allow a list of roles for each menu entry
- [ ] Add translation to missing roles
- [ ] Review the default roles for the default users and groups (users should permissions to access and search)
