### ISSUE TITLE
Change the default destination folder on some plugins

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#638]
AIP export plugin:
- Output folder = ..../transferred-resources/EXPORTS

Inventory report:
- Output folder = ..../transferred-resources/REPORTS

Se tiveres dúvidas avisa...

**Comment by hsilva-keep** [comment]
@jmaferreira Aren't we, with this change, mixing up things? Transferred resources (information to enter the repository) and exports/reports (information to exit the repository)???

**Comment by jmaferreira** [comment]
Yes we are. But what’s the problem with that? Transference is a great area to communicate files with the repository.

Storing files “wherever" in the repository doesn’t seem right (e.g. can be used to overwrite special files), its impractical from the point of view of the user.. etc.

**Comment by hsilva-keep** [comment]
My points are:
- mixing up things will cause confusion on what information is to get in & what information is to get out
- will have impact in reindex operations (whenever reindexing the root is needed)
- everyone who has permissions to transferred resources will be able to access information that probably they shouldn't

**Comment by luis100** [comment]
@jmaferreira is this to be done now?

**Comment by jmaferreira** [comment]
It can wait.

**Comment by jmaferreira** [comment]
A new idea emerged today.
We should have a folder on roda_home where reports produced by plugins could be deposited by default. The UI could be enriched with a way of downloading these reports (something like the transferred resources area, but read-only).

@hsilva-keep what do you think? Any idea of the effort involved?

**Comment by hsilva-keep** [comment]
@jmaferreira Well, if you give it a good thought, a plugin can produce data that can be a report, or several reports or anything else indeed. Having this in mind, and being a plugin executed in a Job context, I would tie/relate this data produced by the plugin (or several plugins) to the Job. And, if it is going to be something like transferred resources, that means that:

1. We need to create a new Model entity (something like JobData), Model logic (at least CRUD) and decide where to store this data (Storage or somewhere else inside roda_home)
2. Have this data indexed (so we can build web interfaces for it, for listing & downloading, ideally accessible through the Job web interface)
3. Create minimal REST API methods (not necessarily CRUD)
4. Change already existing plugins to use this new way to store reports/data (this would prove the concept)

This is "the way" I would pursue to allow plugins to produce data (other than Intelectual Entities) and have that data "connected" to the Job who produced it, and also being able to list & download that same data.

I say "the way" because ATM data produced is all mixed in, with no relation to the Job who produced it & if we are going to add web interface to list & download it cannot the done efficiently by simple listing the contents of a folder.

**Comment by hsilva-keep** [comment]
Ah, and forgot to say something about the effort. 
Being optimistic, considering 1 person fully committed to this task (8 hours a day), would take
-  3 days to do the Model & Index part
- 1 day to tackle the REST API (list data produced by a Job & download a specific file)
- 2 to 3 days to do the web interface part (in a Job context, allow listing & downloading of data produced by Job)
- 1 day to change the plugin that does AIP export & Inventory report

**Comment by jmaferreira** [comment]
@luis100 see if this development helps in your objectives to generate reports.

**Comment by luis100** [comment]
This would help. But this issue has digressed into a completely different feature request. 
Moved this feature request to  #1108
Setting this one as wontfix.
