### ISSUE TITLE
Manage model and index updates

### ISSUE THREAD

**Issue by luis100** [keeps/roda#658]
In every model class, i.e. classes under `org.roda.core.data.v2`, keep track of the class version, example:

``` java
class Report {
  public static int VERSION = 2;
  ...
}
```

On `RODA_HOME`, under data, have a `model.json`, have information that keeps which versions are data in:

``` json
"model": {
  "org.roda.core.data.v2.jobs.Report": 2,
}
```

On startup, this information would be checked on RodaCoreFactory and initialization would not be allowed while data migration was not completed. Scripts for migration would be available for manually upgrading information.

For the index, keep the schema version on the schema name attribute, for example:
`roda-core/roda-core/src/main/resources/config/index/JobReport/conf/schema.xml`

``` xml
<!-- Schema name is the schema version with a prefix -->
<schema name="schema-version-3" version="1.5">
```

The code version can be checked on resources and the installed version can be checked using SolrJ method [SchemaRequest.SchemaName](https://lucene.apache.org/solr/5_5_1/solr-solrj/org/apache/solr/client/solrj/request/schema/SchemaRequest.SchemaName.html).

Again, RodaCoreFactory must check versions on startup and don't allow initialization while schemas are not updated, suggesting instructions on how this could be done manually.

**Comment by luis100** [comment]
Note that versions are integers so partial migrations scripts can be created in the future and their order easily calculated by the version numbers.

Also, some enforcing of the VERSION constant in all model classes may be possible in the IsRODAObject interface.

**Comment by luis100** [comment]
An enhancement would be to also have a version field on every collection, that would state the version that each SOLr document is in. A facet can easily be created that shows how many documents are outdated versions and filtering can be used to easily re-index documents that are not on the current version.

**Comment by hsilva-keep** [comment]
Done since b2075dc3338f625c0c6a694e842a2e237bf8a05b. 

## How does this work?

There is a **MigrationManager** which is responsible for detecting, during RODA startup, if there is differences between installed model classes & code model classes, as well as changes in the index. And if there is, RODA does not start in order to prevent incoherences in the system. 

### For doing model related verifications, the following changes have been made:
- A file called **model.json** is created in **RODA_HOME/data/** and contains a mapping between model class and its version (an integer, starting in 1). We may call this information `installed model class versions`.
- An interface called **IsModelObject** was created mandating model classes that implement it to declare the version. Actual model classes have been changed to follow this logic (e.g. AIP, Representation, File, etc). We may call this information `code model class versions`.

### For doing index related verifications, the following changes have been made:

- Each **schema.xml** file now has the attribute `/schema/@name` set with a value with the syntax `schema-version-X` (where X is an integer). 

## What I have to do when I want to introduce a change in a model class?

The more probable scenario when changing a model class is that the json produced from it changes. And this makes jsons created before this change invalid. Therefore, it is necessary to introduce the required changes in order to make older/already created jsons valid.

1. Increment by one the version of that particular model class (method `getClassVersion`).
2. Create a class that implements the interface `MigrationAction<T extends IsModelObject>`. This is the class responsible to do the set of actions that update model data in order to accommodate the changes you've made in the model class.
3. Head to MigrationManager, and in the method `setupModelMigrations` add a line like the following: `addModelMigration(Job.class, 2, JobToVersion2.class);` which basically is saying `to migrate Job model data to version 2, the code in JobToVersion2 should be executed`.

## How can I apply the configured migrations to be able to start RODA

Grab or generate roda-core-with-dependencies jar file and execute:
```bash
$> java -jar roda-core-with-dependencies*jar migrate model
```

## What I have to do when I want to introduce a change in the index?

The more probable scenario when changing a model class is that the associate index also changes. So, in order to notify that a changes has occurred, edit file **schema.xml** and increment the attribute `/schema/@name` by one.
