### ISSUE TITLE
Review default corpora 

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda#781]
I.e. the corpora used to create AIPs during the first run of RODA.

**Comment by jmaferreira** [comment]
I will add as default corpora the following files:
- SIARD 2.0 Standard
- SIP Format Specification
- AIP Format Specification
- DIP Format Specification

I haven't don't yet because eCH site is buggy at the moment and IP final specifications are going to be published by the end of the week. So.. I will do this next week.

**Comment by luis100** [comment]
Due to a change on the model that requires a migration, a clean instalation of RODA does not start up because it needs a model migration.

This issue has become of the outmost importance, we can't release a version that doesn't work without manual technical intervention.

**Comment by luis100** [comment]
Moved fix by removing corpora to #856, postponing this issue to 2.1

**Comment by jmaferreira** [comment]
This is going to take more time than expected. I don't thing the specs will be officially public soon enough.

Maybe we should think of a different type of corpora.

**Comment by luis100** [comment]
To review this after implementing the representation information feature.

**Comment by jmaferreira** [comment]
Done.

**Comment by hsilva-keep** [comment]
I'll leave the evidence for future screening :) 
![captura de ecra de 2017-10-24 09 59 20](https://user-images.githubusercontent.com/1315759/31933801-1883f502-b8a2-11e7-9ab5-c663cc9d65d1.png)
