### ISSUE TITLE
If we have two descriptive metadata (DC and EAD) with different titles, the second title is not indexed

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#825]
If we search for the title in the second title, it wont be found, not even on simple search.

**Comment by hsilva-keep** [comment]
@jmaferreira well, actually this can be seen as a RODA limitation rather than as a bug, because:
* All RODA indexes that have basic search have a field called search that collect information from the other fields by doing the following (i.e. copy all information from all fields): ```<copyField source="*" dest="search" />```
* AIP object has a single title (and not a list) and because of that we've made title index field non-multivalue
**NOTE:** this behaviour is also applicable to `level`, `dateInitial` and `dateFinal`

Having said that, if all the "titles" should be indexed in order to be indexed, solr title field definition must be changed and guard against it removed from [SolrUtils](https://github.com/keeps/roda/blob/development/roda-core/roda-core/src/main/java/org/roda/core/index/utils/SolrUtils.java#L158). And, what about the other fields?

**Comment by hsilva-keep** [comment]
Currently in RODA version 3, if one AIP has two or more titles, only the first is presented but all are searchable using simple search (in advanced search only the first can be searched).

If no need for this occurred during 2 years, I'm closing the issue without further actions.
