### ISSUE TITLE
When ingesting SIP updates the view created packages ceases to work

### ISSUE THREAD

**Issue by luis100** [keeps/roda#832]
On each AIP keep a list of ingest jobs instead of a single job id, this will allow adding jobs that updated that AIP via a SIP update by adding their id to this list.

This should be retro-compatible so it does not need to migrate all AIPs. (e.g. use another attribute that if does not exist uses the old attribute).

**Comment by hsilva-keep** [comment]
@luis100 calling this an issue is misleading because, as the title of the issue says, it lists the created packages. And when a Job updates an AIP, it is not considered a creation. 
Nevertheless, creating a new attribute to keep the ID of the Jobs that have manipulated somehow the AIP makes perfectly sense and, when viewing a job and clicking that button, the search must be conducted on both the created job id & manipulated job id list.

**Comment by nunovieira220** [comment]
Done on c4fbf767a9d65489a751ccc08d6cbaea0ec14b29
