### ISSUE TITLE
Sorting by columns in some tables is incorrect (e.g. titles in the list of records)

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#95]
Check this
http://stackoverflow.com/questions/7991885/solr-wrong-sort-text-fields

**Comment by hsilva-keep** [comment]
The problem in sorting titles is caused by the fact that title is a field in Apache Solr that is tokenized and that has influence on how sorting is done (see http://stackoverflow.com/questions/7790113/solr-sort-doesnt-work-expectedly).
The solution implemented (305a584cc9fdddbab193401e1be174958283a789) is precisely the same as suggested in the stackoverflow thread, i.e., to have a field just for doing sort on title, field that is automatically filled by Apache Solr via copyfield.
