### ISSUE TITLE
On the demo site, the "Obtain command" is not working

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#996]
![screen shot 2017-05-26 at 09 42 02](https://cloud.githubusercontent.com/assets/3181302/26487489/a4602266-41f7-11e7-913c-97d36fdd5a90.png)

I'm not sure if this is a new bug or an old bug.

**Comment by hsilva-keep** [comment]
This happened before because we have customized roda-wui.properties & therefore the property cannot be found because if the config file exists RODA_HOME, this will be the only file from where we are getting properties & their values. 
I'll create a separate issue to improve the way we lookup for properties in the config files.

**Comment by hsilva-keep** [comment]
This issue has been sorted out, and I've already created an issue to improve the way we load the configs (#998).

**Comment by jmaferreira** [comment]
The application should be able to cope with missing properties… like setting the defaults in the code.

**Comment by jmaferreira** [comment]
Is this fixed on DGLAB?

**Comment by hsilva-keep** [comment]
As I've said before, an issue was created already to better handle the loading of configurations. 
In what concerns DGLAB, yes, the property is there.
